# Do not edit this file.

# This is the main application script. To run your web server (which you
# need to do before you can see your website in a browser), you would run
# `ruby main.rb` in Terminal.

# These lines invoke a tool call Bundler to automatically `require` several
# Ruby scripts that make this Web framework work.
require 'rubygems'
require 'bundler'
Bundler.require

require 'dotenv'
Dotenv.load

# This is an add-on to the Web framework, which scans your code anew each time
# you save it. Otherwise, you would have to `Control + C` to stop the server
# and then run it again--each time you changed your code.
require 'sinatra/reloader'

# This sets up a class called MyApp, which you will use in controllers.
require 'sinatra/base'
class MyApp < Sinatra::Base
  register Sinatra::Reloader
  set :sessions, true
  set :bind, '0.0.0.0'
  set :show_exceptions, true
  set :views, Proc.new { File.join(root, "app", "views") }
end

require 'tilt/erb'
require 'sqlite3'
require 'pry'

# Opens or creates the musicdb database based on if test environment is test or prod.
if MyApp.settings.environment == :test
	DB = SQLite3::Database.new "musicdb_tst.db"
elsif MyApp.settings.environment == :development
	DB = SQLite3::Database.new "musicdb_dev.db"
end

# Create songs table if it doesn't exist.
DB.execute('create table if not exists songs (title varchar(50),artist varchar(50),album varchar(50),genre varchar(50),duration varchar(5),songrating smallint,albumrating smallint,insert_tstamp varchar(25))')

# Setting so query results will return as a hash.
DB.results_as_hash = true

Dir[File.dirname(__FILE__) + '/app/models/*.rb'].each {|file| require file }

Dir[File.dirname(__FILE__) + '/app/controllers/*.rb'].each {|file| require file }

binding.pry
puts 'Done'
